[package]
name = "zakros-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.72"
bstr = { version = "1.6.0", default-features = false }
bytes = "1.4.0"
parking_lot = "0.12.1"
serde = { version = "1.0.180", features = ["derive"] }
thiserror = "1.0.44"
tokio-util = "0.7.8"
