[package]
name = "zakros-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3.5"
async-trait = "0.1.72"
bstr = { version = "1.6.0", default-features = false }
bytes = "1.4.0"
futures = { version = "0.3.28", default-features = false }
parking_lot = "0.12.1"
serde = { version = "1.0.181", features = ["derive"] }
thiserror = "1.0.44"
tokio = { version = "1.29.1", default-features = false, features = ["sync"] }
tokio-util = { version = "0.7.8", features = ["io"] }
