[package]
name = "zakros-raft"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.72"
bincode = "1.3.3"
byteorder = "1.4.3"
bytes = "1.4.0"
futures = { version = "0.3.28", default-features = false }
parking_lot = "0.12.1"
rand = "0.8.5"
serde = { version = "1.0.176", features = ["derive"] }
thiserror = "1.0.44"
tokio = { version = "1.29.1", features = [
	"fs",
	"io-util",
	"macros",
	"parking_lot",
] }
tokio-util = "0.7.8"
tracing = "0.1.37"
